ration') ON DUPLICATE KEY UPDATE sample_id=sample_id;
INSERT INTO sample (disease_id, patient_code, tissue_source, category, sample_type, notes) VALUES ( (SELECT disease_id FROM disease WHERE disease_name='Systemic lupus erythematosus' LIMIT 1), 'refractory systemic lupus erythematosus with monocytosis exhibiting somatic KRAS mutation', 'unknown', 'unknown', 'unknown', 'AUTO: placeholder sample for literature curation') ON DUPLICATE KEY UPDATE sample_id=sample_id;
INSERT INTO sample (disease_id, patient_code, tissue_source, category, sample_type, notes) VALUES ( (SELECT disease_id FROM disease WHERE disease_name='Rheumatoid arthritis' LIMIT 1), 'Activating STAT3 mutations in CD8+ T-cells correlate to serological positivity in rheumatoid arthritis', 'unknown'-- 010_seed_literature_driver_variants_v1.sql
-- Loads literature_driver_variants_v1.xlsx into core tables.
-- NOTE: This creates placeholder sample + sequencing_experiment rows (1 per study_short + disease).
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

-- ------------------------------------------------------------
-- 1) Create placeholder samples per (study_name_short, disease)
-- ------------------------------------------------------------
INSERT INTO sample (disease_id, patient_code, tissue_source, category, sample_type, notes) VALUES ( (SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1), 'Somatic mutations increase hepatic clonal fitness', 'unknown', 'unknown', 'unknown', 'AUTO: placeholder sample for literature cu, 'unknown', 'unknown', 'AUTO: placeholder sample for literature curation') ON DUPLICATE KEY UPDATE sample_id=sample_id;

-- ------------------------------------------------------------
-- 2) Create sequencing_experiment rows per combo
--    technology is set to 'Other' by default; edit later if needed.
-- ------------------------------------------------------------
INSERT INTO sequencing_experiment (study_id, sample_id, technology, coverage, notes) VALUES ( (SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1), (SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1), 'Other', NULL, 'AUTO: placeholder sequencing_experiment for literature curation') ON DUPLICATE KEY UPDATE seq_exp_id=seq_exp_id;
INSERT INTO sequencing_experiment (study_id, sample_id, technology, coverage, notes) VALUES ( (SELECT study_id FROM study WHERE study_name='refractory systemic lupus erythematosus with monocytosis exhibiting somatic KRAS mutation' LIMIT 1), (SELECT sample_id FROM sample WHERE patient_code='refractory systemic lupus erythematosus with monocytosis exhibiting somatic KRAS mutation' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Systemic lupus erythematosus' LIMIT 1) LIMIT 1), 'Other', NULL, 'AUTO: placeholder sequencing_experiment for literature curation') ON DUPLICATE KEY UPDATE seq_exp_id=seq_exp_id;
INSERT INTO sequencing_experiment (study_id, sample_id, technology, coverage, notes) VALUES ( (SELECT study_id FROM study WHERE study_name='Activating STAT3 mutations in CD8+ T-cells correlate to serological positivity in rheumatoid arthritis' LIMIT 1), (SELECT sample_id FROM sample WHERE patient_code='Activating STAT3 mutations in CD8+ T-cells correlate to serological positivity in rheumatoid arthritis' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Rheumatoid arthritis' LIMIT 1) LIMIT 1), 'Other', NULL, 'AUTO: placeholder sequencing_experiment for literature curation') ON DUPLICATE KEY UPDATE seq_exp_id=seq_exp_id;

-- ------------------------------------------------------------
-- 3) Insert genes / variants / annotations / calls
-- ------------------------------------------------------------
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'ARID1A' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='ARID1A' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr4', 3015470, 'CA', 'C', 'somatic', 'Zhu M et al; Cell 2019' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr4' AND pos=3015470 AND ref='CA' AND alt='C' LIMIT 1), NULL, 'frameshift substitution', 'c.3210_3211delC', NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr4' AND pos=3015470 AND ref='CA' AND alt='C' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'ARID1B' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='ARID1B' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr6', 157775677, 'C', 'T', 'somatic', 'Zhu M et al; Cell 2020' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr6' AND pos=157775677 AND ref='C' AND alt='T' LIMIT 1), NULL, 'nonsense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr6' AND pos=157775677 AND ref='C' AND alt='T' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'KMT2D' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='KMT2D' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr12', 49814389, 'G', 'A', 'somatic', 'Zhu M et al; Cell 2021' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr12' AND pos=49814389 AND ref='G' AND alt='A' LIMIT 1), NULL, 'missense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr12' AND pos=49814389 AND ref='G' AND alt='A' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'KMT2C' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='KMT2C' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr7', 151615774, 'G', 'T', 'somatic', 'Zhu M et al; Cell 2022' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr7' AND pos=151615774 AND ref='G' AND alt='T' LIMIT 1), NULL, 'missense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr7' AND pos=151615774 AND ref='G' AND alt='T' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'TP53' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='TP53' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr17', 7480438, 'C', 'T', 'somatic', 'Zhu M et al; Cell 2023' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr17' AND pos=7480438 AND ref='C' AND alt='T' LIMIT 1), NULL, 'missense SNV', 'c.743G>A', 'p.R248Q', 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr17' AND pos=7480438 AND ref='C' AND alt='T' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'TP53' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='TP53' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr17', 7482700, 'G', 'GT', 'somatic', 'Zhu M et al; Cell 2024' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr17' AND pos=7482700 AND ref='G' AND alt='GT' LIMIT 1), NULL, 'frameshift insertion', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr17' AND pos=7482700 AND ref='G' AND alt='GT' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'CTNNB1' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='CTNNB1' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr3', 41307591, 'T', 'C', 'somatic', 'Zhu M et al; Cell 2025' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr3' AND pos=41307591 AND ref='T' AND alt='C' LIMIT 1), NULL, 'missense SNV', 'c.134C>T', 'p.S45F', 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr3' AND pos=41307591 AND ref='T' AND alt='C' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'CTNNB1' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='CTNNB1' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr3', 41307594, 'G', 'A', 'somatic', 'Zhu M et al; Cell 2026' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr3' AND pos=41307594 AND ref='G' AND alt='A' LIMIT 1), NULL, 'missense SNV', 'c.121A>G', 'p.T41A', 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr3' AND pos=41307594 AND ref='G' AND alt='A' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'NOTCH1' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='NOTCH1' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr1', 144986523, 'G', 'A', 'somatic', 'Zhu M et al; Cell 2027' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr1' AND pos=144986523 AND ref='G' AND alt='A' LIMIT 1), NULL, 'nonsense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr1' AND pos=144986523 AND ref='G' AND alt='A' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'NOTCH2' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='NOTCH2' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr3', 52468155, 'G', 'T', 'somatic', 'Zhu M et al; Cell 2028' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr3' AND pos=52468155 AND ref='G' AND alt='T' LIMIT 1), NULL, 'missense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr3' AND pos=52468155 AND ref='G' AND alt='T' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'BAP1' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='BAP1' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr19', 11185404, 'C', 'A', 'somatic', 'Zhu M et al; Cell 2029' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr19' AND pos=11185404 AND ref='C' AND alt='A' LIMIT 1), NULL, 'nonsense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr19' AND pos=11185404 AND ref='C' AND alt='A' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'SMARCA4' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='SMARCA4' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr22', 24555320, 'C', 'T', 'somatic', 'Zhu M et al; Cell 2030' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr22' AND pos=24555320 AND ref='C' AND alt='T' LIMIT 1), NULL, 'missense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr22' AND pos=24555320 AND ref='C' AND alt='T' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1), 'SMARCB1' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='SMARCB1' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1), 'chr22', 24159352, 'C', 'T', 'somatic', 'Zhu M et al; Cell 2031' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) AND chrom='chr22' AND pos=24159352 AND ref='C' AND alt='T' LIMIT 1), NULL, 'nonsense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) AND chrom='chr22' AND pos=24159352 AND ref='C' AND alt='T' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'KDM6A' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='KDM6A' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr16', 3828440, 'G', 'A', 'somatic', 'Zhu M et al; Cell 2032' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr16' AND pos=3828440 AND ref='G' AND alt='A' LIMIT 1), NULL, 'frameshift deletion', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr16' AND pos=3828440 AND ref='G' AND alt='A' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'CREBBP' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='CREBBP' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr22', 41928765, 'T', 'G', 'somatic', 'Zhu M et al; Cell 2033' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr22' AND pos=41928765 AND ref='T' AND alt='G' LIMIT 1), NULL, 'missense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr22' AND pos=41928765 AND ref='T' AND alt='G' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'EP300' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='EP300' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr4', 107076476, 'C', 'T', 'somatic', 'Zhu M et al; Cell 2034' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr4' AND pos=107076476 AND ref='C' AND alt='T' LIMIT 1), NULL, 'missense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr4' AND pos=107076476 AND ref='C' AND alt='T' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'TET2' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='TET2' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr2', 25680040, 'C', 'T', 'somatic', 'Zhu M et al; Cell 2035' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr2' AND pos=25680040 AND ref='C' AND alt='T' LIMIT 1), NULL, 'nonsense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr2' AND pos=25680040 AND ref='C' AND alt='T' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'DNMT3A' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='DNMT3A' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr3', 47114096, 'G', 'A', 'somatic', 'Zhu M et al; Cell 2036' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr3' AND pos=47114096 AND ref='G' AND alt='A' LIMIT 1), NULL, 'missense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr3' AND pos=47114096 AND ref='G' AND alt='A' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'SETD2' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='SETD2' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr10', 91471575, 'G', 'T', 'somatic', 'Zhu M et al; Cell 2037' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr10' AND pos=91471575 AND ref='G' AND alt='T' LIMIT 1), NULL, 'frameshift deletion', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr10' AND pos=91471575 AND ref='G' AND alt='T' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'ASXL1' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='ASXL1' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr13', 49516564, 'C', 'T', 'somatic', 'Zhu M et al; Cell 2038' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr13' AND pos=49516564 AND ref='C' AND alt='T' LIMIT 1), NULL, 'frameshift deletion', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr13' AND pos=49516564 AND ref='C' AND alt='T' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'PTEN' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='PTEN' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr17', 29649637, 'G', 'A', 'somatic', 'Zhu M et al; Cell 2039' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr17' AND pos=29649637 AND ref='G' AND alt='A' LIMIT 1), NULL, 'missense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr17' AND pos=29649637 AND ref='G' AND alt='A' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'RB1' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='RB1' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1), 'chr3', 178653879, 'A', 'G', 'somatic', 'Zhu M et al; Cell 2040' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr3' AND pos=178653879 AND ref='A' AND alt='G' LIMIT 1), NULL, 'nonsense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh37' LIMIT 1) AND chrom='chr3' AND pos=178653879 AND ref='A' AND alt='G' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1), 'NF1' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='NF1' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1), 'chr17', 31322619, 'G', 'A', 'somatic', 'Zhu M et al; Cell 2041' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) AND chrom='chr17' AND pos=31322619 AND ref='G' AND alt='A' LIMIT 1), NULL, 'missense SNV', NULL, NULL, 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) AND chrom='chr17' AND pos=31322619 AND ref='G' AND alt='A' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1), 'PIK3CA' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='PIK3CA' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1), 'chr3', 178936091, 'A', 'G', 'somatic', 'Zhu M et al; Cell 2042' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) AND chrom='chr3' AND pos=178936091 AND ref='A' AND alt='G' LIMIT 1), NULL, 'missense SNV', 'c.3140A>G', 'p.H1047R', 'paper', NULL, 'is_driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Somatic mutations increase hepatic clonal fitness' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Somatic mutations increase hepatic clonal fitness' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Chronic liver disease' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='Hepatocyte' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) AND chrom='chr3' AND pos=178936091 AND ref='A' AND alt='G' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Recurrent candidate fitness driver; evidence=Recurrent in hepatocyte clones; highlighted in paper as recurrent in ultradeep panel' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1), 'KRAS' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='KRAS' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1), 'chr12', 25245350, 'C', 'T', 'somatic', 'Paper reports somatic KRAS mutation without specifying reference genome or genomic coordinates; genomic coordinates shown are curator-derived from HGVS/transcript annotation and reference genome.' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) AND chrom='chr12' AND pos=25245350 AND ref='C' AND alt='T' LIMIT 1), NULL, 'SNV (missense)', 'c.35G>A', 'p.G12D', 'paper', NULL, 'is_driver=Established oncogenic driver; evidence=Observed clonal event + strong prior driver evidence (oncogenic hotspot)' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='refractory systemic lupus erythematosus with monocytosis exhibiting somatic KRAS mutation' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='refractory systemic lupus erythematosus with monocytosis exhibiting somatic KRAS mutation' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Systemic lupus erythematosus' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='CD14+ monocytes' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) AND chrom='chr12' AND pos=25245350 AND ref='C' AND alt='T' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Established oncogenic driver; evidence=Observed clonal event + strong prior driver evidence (oncogenic hotspot)' ) ON DUPLICATE KEY UPDATE call_id=call_id;
INSERT INTO genes (ref_genome_id, gene_symbol) VALUES ( (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1), 'STAT3' ) ON DUPLICATE KEY UPDATE gene_id=gene_id;
INSERT INTO variants (gene_id, ref_genome_id, chrom, pos, ref, alt, variant_origin, notes) VALUES ( (SELECT gene_id FROM genes WHERE gene_symbol='STAT3' AND ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) LIMIT 1), (SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1), 'chr17', 42322464, 'T', 'A', 'somatic', 'Paper reports STAT3 variants by ddPCR using HGVS notation only; genomic coordinates shown are curator-derived coordinates from transcript NM_139276.3 and were not reported by the paper.' ) ON DUPLICATE KEY UPDATE notes=COALESCE(VALUES(notes), notes);
INSERT INTO variant_annotation (variant_id, protein_domain_id, consequence, hgvsc, hgvsp, source, ann_tool_version, notes) VALUES ( (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) AND chrom='chr17' AND pos=42322464 AND ref='T' AND alt='A' LIMIT 1), NULL, 'missense SNV', 'c.1919A>T', 'p.Tyr640Phe (Y640F)', 'paper', NULL, 'is_driver=Established activating driver; evidence=Functional + observational' ) ON DUPLICATE KEY UPDATE ann_id=ann_id;
INSERT INTO sample_variant_call (seq_exp_id, cell_type_id, variant_id, vaf, variant_origin, depth, genotype_qual, notes) VALUES ( (SELECT seq_exp_id FROM sequencing_experiment WHERE study_id=(SELECT study_id FROM study WHERE study_name='Activating STAT3 mutations in CD8+ T-cells correlate to serological positivity in rheumatoid arthritis' LIMIT 1) AND sample_id=(SELECT sample_id FROM sample WHERE patient_code='Activating STAT3 mutations in CD8+ T-cells correlate to serological positivity in rheumatoid arthritis' AND disease_id=(SELECT disease_id FROM disease WHERE disease_name='Rheumatoid arthritis' LIMIT 1) LIMIT 1) LIMIT 1), (SELECT cell_type_id FROM cell_type WHERE cell_type_name='CD8+ T cell (peripheral blood)' LIMIT 1), (SELECT variant_id FROM variants WHERE ref_genome_id=(SELECT ref_genome_id FROM reference_genome WHERE ref_genome_name='GRCh38' LIMIT 1) AND chrom='chr17' AND pos=42322464 AND ref='T' AND alt='A' LIMIT 1), NULL, 'somatic', NULL, NULL, 'driver=Established activating driver; evidence=Functional + observational' ) ON DUPLICATE KEY UPDATE call_id=call_id;

SET FOREIGN_KEY_CHECKS=1;
